### ISSUE TITLE
Punctuation notes/questions to review

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/alain-rene-lesage_gil-blas_tobias-smollett#1]
While reading Gil Blas for quotation marks, I'm noticing some unrelated issues that might be OCR errors or similar. I prefer to log this kind of thing as issues in GitHub so I don't forget to come back to them later. GitHub doesn't allow issues on a fork of another project, so please forgive me for dropping these here in the main project. I'll come back to look at them more closely after finishing the quotation mark read-through. I'll update this comment with new entries as I find them.

chapter-8-9: Colon should be semi-colon?
`"I shall be very much obliged to you," answered I: "your introduction is sufficient."`

chapter-8-10: Comma should be period?
`conquest of me by her prattle, I began to launch out`

chapter-8-10: Colon should be semi-colon?
`"I really am not in so merry a mood, madam," exclaimed I: "it is a plain matter`

chapter-9-1: Colon should be semi-colon?
`"This is not all," resumed Scipio: "Señor Gabriel hopes`

chapter-9-3: Not sure about the combination of quotes, emphasis, and final period here. Is emphasis still needed when adding quotes? Is it weird to end this (apparently) shouted phrase with a period?
`when fifteen or twenty men, some on foot and some on horseback, all with swords and firearms, surrounded and stopped the coach, crying out, "<em>In the name of our sovereign lord the king</em>."`

chapter-9-6: "her" should be "he"?
`"Don Gastón," cried her as he arrested my uplifted arm`

chapter-9-7: Colon could be semi-colon?
`neither household nor house," answered he: "to spare you`

**Comment by acabal** [comment]
No problem, thanks. If you could confirm them against the scans at the end, that would be very helpful!

**Comment by tuskpot** [comment]
After reviewing, there are two items that need a fix. Can I include these as a separate commit on the dialogue pull request, or would you rather handle them differently?

**Comment by acabal** [comment]
You can include them in the dialog PR

**Comment by acabal** [comment]
I lost track, were these all fixed in your PR? If so then you can close this.

**Comment by tuskpot** [comment]
Yep, these are resolved. Thanks.
