### ISSUE TITLE
Separate ligatures

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/alain-rene-lesage_gil-blas_tobias-smollett#2]
There are a handful of `æ` ligatures throughout the book. These should be separated to `ae`, right?

A few examples:

- they took me for the coryphæus of the opera
- the canine <i xml:lang="la">amicus curiæ</i> set his fangs
- Don Gæsar, who came backwards and forwards

**Comment by acabal** [comment]
Thanks, I've converted them
